XGBoost:
  learning_rate: 0.1
  n_estimators: 1000
  max_depth: 7
  min_child_weight: 3
  gamma: 0
  subsample: 0.8
  colsample_bytree: 0.8
  objective: 'binary:logistic'
  nthread: 4
  scale_pos_weight: 1
  seed: 27