artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/JuliusHmto/data-sources/releases/download/v1.0.0/SBAnational.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/SBAnational.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/SBAnational.csv
  train_columns: artifacts/data_transformation/train_columns.csv


model_trainer:
  root_dir: artifacts/model_trainer
  x_train_data_path: artifacts/data_transformation/X_train.csv
  x_test_data_path: artifacts/data_transformation/X_test.csv
  y_train_data_path: artifacts/data_transformation/y_train.csv
  y_test_data_path: artifacts/data_transformation/y_test.csv
  model_name: model.joblib


model_evaluation:
  root_dir: artifacts/model_evaluation
  x_test_data_path: artifacts/data_transformation/X_test.csv
  y_test_data_path: artifacts/data_transformation/y_test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json